#!/usr/bin/env python3
"""Pre-generate English MP3 audio for every sight word using Edge-TTS.

Run from repo root or scripts/. Output:
  public/audio/<word>.mp3
  src/data/audioManifest.json  (list of words successfully generated)

Used by the GitHub Actions deploy workflow before `npm run build`.

Per-letter MP3s are generated by asking Aria to read "letter A" and
trimming the leading "letter " off with ffmpeg silencedetect — Aria
pronounces a bare single letter as the article ("uh") rather than the
letter name, so we need to put it in context and then clip.
"""
import asyncio
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WORDS_FILE = REPO_ROOT / 'src/data/words.ts'
OUT_DIR = REPO_ROOT / 'public/audio'
TMP_DIR = REPO_ROOT / 'public/audio/_tmp'
MANIFEST_PATH = REPO_ROOT / 'src/data/audioManifest.json'

VOICE = 'en-US-AriaNeural'  # natural-sounding kid-friendly female voice
RATE = '-15%'                # a bit slower for kids
LETTERS = 'abcdefghijklmnopqrstuvwxyz'

# Aria reads bare "A" as the article /ə/, not the letter name /eɪ/. Putting
# the letter inside "letter <X>" gets the correct pronunciation; ffmpeg then
# trims the leading "letter " word.
def letter_prompt(letter: str) -> str:
    return f'letter {letter.upper()}'


# Fallback trim offset (seconds) used when silence detection can't find the
# natural pause between "letter" and the letter name. At rate=-15% Aria's
# "letter " takes roughly 380-450ms.
LETTER_PREFIX_FALLBACK = 0.42


def parse_words() -> list[str]:
    text = WORDS_FILE.read_text(encoding='utf-8')
    # Words are in arrays like ['I', 'a', 'is', ...]
    matches = re.findall(r"'([A-Za-z]+)'", text)
    seen: dict[str, None] = {}
    for w in matches:
        if w not in seen:
            seen[w] = None
    return list(seen.keys())


def find_first_silence_end(audio_path: Path) -> float | None:
    """Return the timestamp (s) at which the first silence in `audio_path`
    ends. Used to locate the gap between "letter" and the letter name.
    Returns None if ffmpeg isn't available or no silence is detected."""
    if shutil.which('ffmpeg') is None:
        return None
    try:
        det = subprocess.run(
            [
                'ffmpeg', '-hide_banner', '-nostats',
                '-i', str(audio_path),
                '-af', 'silencedetect=noise=-30dB:d=0.05',
                '-f', 'null', '-',
            ],
            capture_output=True, text=True, check=False,
        )
    except Exception as e:  # pragma: no cover
        print(f'  ffmpeg silencedetect failed for {audio_path.name}: {e}', file=sys.stderr)
        return None
    for line in det.stderr.splitlines():
        if 'silence_end' in line:
            # "[silencedetect ...] silence_end: 0.50 | silence_duration: 0.07"
            try:
                tail = line.split('silence_end:')[1].strip()
                return float(tail.split('|')[0].strip())
            except (IndexError, ValueError):
                continue
    return None


def trim_letter_prefix(src_path: Path, dst_path: Path) -> bool:
    """Trim the "letter " prefix off a `letter X` MP3 and write to dst_path.
    Uses ffmpeg silencedetect to find the natural gap; falls back to a fixed
    offset. If ffmpeg isn't available, copies the source verbatim so the cue
    is at least audible (says "letter A" instead of "A")."""
    if shutil.which('ffmpeg') is None:
        # No ffmpeg — best we can do is keep the "letter X" audio
        dst_path.write_bytes(src_path.read_bytes())
        return True
    offset = find_first_silence_end(src_path) or LETTER_PREFIX_FALLBACK
    try:
        # Stream-copy (no re-encode) so we don't depend on libmp3lame being
        # present in the runner's ffmpeg build. -ss after -i seeks on the
        # decoded stream and copies from the nearest mp3 frame >= offset.
        subprocess.run(
            [
                'ffmpeg', '-hide_banner', '-nostats', '-y',
                '-i', str(src_path),
                '-ss', f'{offset:.3f}',
                '-codec:a', 'copy',
                str(dst_path),
            ],
            capture_output=True, text=True, check=True,
        )
        print(f'  trim {src_path.name} from {offset:.3f}s -> {dst_path.name}')
    except subprocess.CalledProcessError as e:
        print(f'  ffmpeg trim failed for {src_path.name}: {e.stderr[:200]}', file=sys.stderr)
        # Fall back to untrimmed audio rather than dropping the cue entirely.
        dst_path.write_bytes(src_path.read_bytes())
        return True
    return dst_path.exists() and dst_path.stat().st_size > 500


async def synth_one(
    manifest_key: str,
    spoken_text: str,
    file_stem: str,
    sem: asyncio.Semaphore,
    trim_prefix: bool = False,
) -> tuple[str, bool]:
    """Generate one MP3.

    manifest_key: identifier appended to the audio manifest (and used as the
                  lookup key in the app, e.g. 'the' or 'letter-a').
    spoken_text:  text passed to the TTS engine ('the', 'letter A', ...).
    file_stem:    on-disk filename stem under OUT_DIR (without .mp3).
    trim_prefix:  when True, generate to a tmp file and trim the "letter "
                  word off via ffmpeg before writing to the final path.
    """
    import edge_tts
    final_path = OUT_DIR / f'{file_stem}.mp3'
    if final_path.exists() and final_path.stat().st_size > 500:
        return manifest_key, True
    gen_path = (TMP_DIR / f'{file_stem}.mp3') if trim_prefix else final_path
    async with sem:
        last_err: Exception | None = None
        for attempt in range(1, 4):
            try:
                communicate = edge_tts.Communicate(spoken_text, VOICE, rate=RATE)
                await communicate.save(str(gen_path))
                ok = gen_path.exists() and gen_path.stat().st_size > 500
                if ok and trim_prefix:
                    ok = trim_letter_prefix(gen_path, final_path)
                if ok:
                    print(f'  OK  {manifest_key!r:>14} -> {final_path.name}')
                    return manifest_key, True
                last_err = RuntimeError('empty file')
            except Exception as e:
                last_err = e
            await asyncio.sleep(0.5 * attempt)
        print(f'  ERR {manifest_key!r}: {last_err}', file=sys.stderr)
        return manifest_key, False


async def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    TMP_DIR.mkdir(parents=True, exist_ok=True)
    words = parse_words()
    # Schedule words and per-letter announcements together. Letter names are
    # stored as 'letter-<a-z>.mp3' with manifest key 'letter-<a-z>' so they
    # don't collide with the sight word "a".
    # tuple: (manifest_key, spoken_text, file_stem, trim_prefix)
    tasks: list[tuple[str, str, str, bool]] = []
    for w in words:
        key = w.lower()
        tasks.append((key, w, key, False))
    for letter in LETTERS:
        tasks.append((f'letter-{letter}', letter_prompt(letter), f'letter-{letter}', True))

    print(
        f'Generating audio: {len(words)} sight words + '
        f'{len(LETTERS)} letters -> {OUT_DIR}'
    )
    sem = asyncio.Semaphore(4)
    results = await asyncio.gather(
        *[synth_one(k, t, s, sem, tp) for k, t, s, tp in tasks]
    )
    # Clean up the tmp dir so it isn't shipped in the build artifact.
    if TMP_DIR.exists():
        shutil.rmtree(TMP_DIR, ignore_errors=True)
    manifest = [k for k, ok in results if ok]
    MANIFEST_PATH.write_text(json.dumps(sorted(manifest)), encoding='utf-8')
    failed = [k for k, ok in results if not ok]
    print(f'Wrote manifest: {len(manifest)} / {len(tasks)} entries')
    if failed:
        print(f'  {len(failed)} entry(ies) failed (browser TTS will be used as fallback): {failed}')
    # Always succeed: missing audio falls back to Web Speech API in the app.
    return 0


if __name__ == '__main__':
    sys.exit(asyncio.run(main()))
