#!/usr/bin/env python3
"""Pre-generate English MP3 audio for every sight word using Edge-TTS.

Run from repo root or scripts/. Output:
  public/audio/<word>.mp3
  src/data/audioManifest.json  (list of words successfully generated)

Used by the GitHub Actions deploy workflow before `npm run build`.

Per-letter MP3s are generated by asking Aria to read "letter A" and
trimming the leading "letter " off with ffmpeg silencedetect — Aria
pronounces a bare single letter as the article ("uh") rather than the
letter name, so we need to put it in context and then clip.
"""
import asyncio
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WORDS_FILE = REPO_ROOT / 'src/data/words.ts'
OUT_DIR = REPO_ROOT / 'public/audio'
TMP_DIR = REPO_ROOT / 'public/audio/_tmp'
MANIFEST_PATH = REPO_ROOT / 'src/data/audioManifest.json'

VOICE = 'en-US-AriaNeural'  # natural-sounding kid-friendly female voice
RATE = '-15%'                # a bit slower for kids
LETTERS = 'abcdefghijklmnopqrstuvwxyz'

# Aria reads bare "A" as the article /ə/, not the letter name /eɪ/. Putting
# the letter inside "letter <X>" gets the correct pronunciation; ffmpeg then
# trims the leading "letter " word.
def letter_prompt(letter: str) -> str:
    return f'letter {letter.upper()}'


# Fixed trim offset (seconds) used to remove the leading "letter " word.
# At rate=-15% Aria reads "letter " in ~430-460ms; 0.46s lops it off
# cleanly without eating into the letter name that follows. Silence-based
# detection was unreliable (Aria prepends ~80ms of leading silence which
# silencedetect was mistakenly latching onto), so we just trust the timing.
LETTER_TRIM_OFFSET = 0.46


def parse_words() -> list[str]:
    text = WORDS_FILE.read_text(encoding='utf-8')
    # Words are in arrays like ['I', 'a', 'is', ...]
    matches = re.findall(r"'([A-Za-z]+)'", text)
    seen: dict[str, None] = {}
    for w in matches:
        if w not in seen:
            seen[w] = None
    return list(seen.keys())


def trim_letter_prefix(src_path: Path, dst_path: Path) -> bool:
    """Trim a fixed LETTER_TRIM_OFFSET seconds off the start of src_path and
    write to dst_path. Loud, explicit logging so we can see in the deploy
    log exactly whether the trim ran or fell back to untrimmed audio."""
    ffmpeg_bin = shutil.which('ffmpeg')
    if ffmpeg_bin is None:
        print(
            f'  TRIM SKIP {src_path.name}: ffmpeg not found; shipping "letter X"',
            file=sys.stderr,
        )
        dst_path.write_bytes(src_path.read_bytes())
        return True
    # -ss BEFORE -i: input seek, fast for mp3. -codec:a copy: no re-encode,
    # so we don't depend on libmp3lame. Trimmed file starts at the nearest
    # mp3 frame >= LETTER_TRIM_OFFSET (frame granularity ~26ms).
    cmd = [
        ffmpeg_bin, '-hide_banner', '-nostats', '-y',
        '-ss', f'{LETTER_TRIM_OFFSET:.3f}',
        '-i', str(src_path),
        '-codec:a', 'copy',
        str(dst_path),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if proc.returncode != 0 or not dst_path.exists() or dst_path.stat().st_size <= 500:
        print(
            f'  TRIM FAIL {src_path.name}: rc={proc.returncode}; '
            f'stderr={proc.stderr.strip()[-200:]}',
            file=sys.stderr,
        )
        dst_path.write_bytes(src_path.read_bytes())
        return True
    print(
        f'  TRIM OK   {src_path.name} -> {dst_path.name} '
        f'(start={LETTER_TRIM_OFFSET}s, size={dst_path.stat().st_size}B)'
    )
    return True


async def synth_one(
    manifest_key: str,
    spoken_text: str,
    file_stem: str,
    sem: asyncio.Semaphore,
    trim_prefix: bool = False,
) -> tuple[str, bool]:
    """Generate one MP3.

    manifest_key: identifier appended to the audio manifest (and used as the
                  lookup key in the app, e.g. 'the' or 'letter-a').
    spoken_text:  text passed to the TTS engine ('the', 'letter A', ...).
    file_stem:    on-disk filename stem under OUT_DIR (without .mp3).
    trim_prefix:  when True, generate to a tmp file and trim the "letter "
                  word off via ffmpeg before writing to the final path.
    """
    import edge_tts
    final_path = OUT_DIR / f'{file_stem}.mp3'
    if final_path.exists() and final_path.stat().st_size > 500:
        return manifest_key, True
    gen_path = (TMP_DIR / f'{file_stem}.mp3') if trim_prefix else final_path
    async with sem:
        last_err: Exception | None = None
        for attempt in range(1, 4):
            try:
                communicate = edge_tts.Communicate(spoken_text, VOICE, rate=RATE)
                await communicate.save(str(gen_path))
                ok = gen_path.exists() and gen_path.stat().st_size > 500
                if ok and trim_prefix:
                    ok = trim_letter_prefix(gen_path, final_path)
                if ok:
                    print(f'  OK  {manifest_key!r:>14} -> {final_path.name}')
                    return manifest_key, True
                last_err = RuntimeError('empty file')
            except Exception as e:
                last_err = e
            await asyncio.sleep(0.5 * attempt)
        print(f'  ERR {manifest_key!r}: {last_err}', file=sys.stderr)
        return manifest_key, False


async def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    TMP_DIR.mkdir(parents=True, exist_ok=True)
    words = parse_words()
    # Schedule words and per-letter announcements together. Letter names are
    # stored as 'letter-<a-z>.mp3' with manifest key 'letter-<a-z>' so they
    # don't collide with the sight word "a".
    # tuple: (manifest_key, spoken_text, file_stem, trim_prefix)
    tasks: list[tuple[str, str, str, bool]] = []
    for w in words:
        key = w.lower()
        tasks.append((key, w, key, False))
    for letter in LETTERS:
        tasks.append((f'letter-{letter}', letter_prompt(letter), f'letter-{letter}', True))

    print(
        f'Generating audio: {len(words)} sight words + '
        f'{len(LETTERS)} letters -> {OUT_DIR}'
    )
    sem = asyncio.Semaphore(4)
    results = await asyncio.gather(
        *[synth_one(k, t, s, sem, tp) for k, t, s, tp in tasks]
    )
    # Clean up the tmp dir so it isn't shipped in the build artifact.
    if TMP_DIR.exists():
        shutil.rmtree(TMP_DIR, ignore_errors=True)
    manifest = [k for k, ok in results if ok]
    MANIFEST_PATH.write_text(json.dumps(sorted(manifest)), encoding='utf-8')
    failed = [k for k, ok in results if not ok]
    print(f'Wrote manifest: {len(manifest)} / {len(tasks)} entries')
    if failed:
        print(f'  {len(failed)} entry(ies) failed (browser TTS will be used as fallback): {failed}')
    # Always succeed: missing audio falls back to Web Speech API in the app.
    return 0


if __name__ == '__main__':
    sys.exit(asyncio.run(main()))
